# JVM 内存与编码
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
# 构建缓存（加速增量构建）
org.gradle.caching=true
# 并行构建
org.gradle.parallel=true
# AndroidX
android.useAndroidX=true
# AGP 8.5 can compile against newer SDKs, but it has only been certified up to 34.
android.suppressUnsupportedCompileSdk=36
# R 类非传递，减小体积、加快编译
android.nonTransitiveRClass=true
# Kotlin 官方代码风格
kotlin.code.style=official
